obj-y += irq.o
obj-y += io.o

obj-${CONFIG_MACH_HARMONY} += board-harmony.o

obj-$(CONFIG_ARCH_TEGRA_2x_SOC)         += idle-t2.o
obj-$(CONFIG_ARCH_TEGRA_2x_SOC)         += clock.o
obj-$(CONFIG_ARCH_TEGRA_2x_SOC)         += tegra2_clocks.o
obj-$(CONFIG_ARCH_TEGRA_2x_SOC)         += timer.o
